# Generated by Django 3.0.7 on 2020-06-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_juego_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='precios',
            new_name='precio',
        ),
    ]
