# Generated by Django 3.0.7 on 2020-06-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200616_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='existencia',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
